# Add the `topic:rust` label if the content contains 'rust'
topic:rust:
  - "/(rust)/i"

# Add the `topic:security` label if the issue content contains 'security' or 'secure'
topic:security:
  - "/(security)/i"
  - "/(secure)/i"

# Add the `topic:stability` label if the issue content contains 'crash' or 'panic'
topic:stability:
  - "/(crash)/i"
  - "/(panic)/i"
