#
# Production image (built on the CI environment)
#
FROM --platform=$TARGETPLATFORM debian:bookworm-slim AS prod-ci

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

ARG ARTIFACT_PREFIX

USER root

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends ca-certificates openssl

COPY ${ARTIFACT_PREFIX}.${TARGETOS}-${TARGETARCH}/suzhaobao /suzhaobao


RUN chmod +x /suzhaobao

VOLUME /data /logs

EXPOSE 5800

ENTRYPOINT ["/suzhaobao"]
