on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The name of this release environment. It can be a 'nightly', 'beta' or 'release'"
      git-ref:
        required: true
        type: string
        description: "The github ref to checkout for building the Docker images."
      tag-prefix:
        required: true
        type: string
        description: "The prefix of the Docker image tag. i.e. 'nightly' for 'micross/suzhaobao:nightly-dev'."
      build:
        required: false
        type: boolean
        default: true
        description: "Build the Docker images."
      push:
        required: false
        type: boolean
        default: false
        description: "Publish the Docker images."
      latest:
        required: false
        type: boolean
        default: false
        description: "Update the latest tag of the Docker image."
    secrets:
      DOCKER_HUB_USERNAME:
        required: false
      DOCKER_HUB_TOKEN:
        required: false

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare steps
    runs-on: ubuntu-latest
    outputs:
      tag-prefix: ${{ steps.tag-prefix.outputs.tag-prefix }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Sanitize tag name
        id: tag-prefix
        run: |
          echo "tag-prefix=$(echo '${{ inputs.tag-prefix }}' | sed 's/[^a-zA-Z0-9_.-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Define matrix here so we don't need to search for it when making changes
      - name: Set matrix
        id: set-matrix
        env:
          MATRIX: |
            include:
              # Prod image
              - &base_image
                name: Prod image
                build-target: prod-ci

        run: |
          echo '${{ env.MATRIX }}' > matrix.yaml
          echo "matrix=$(yq -o json -I=0 matrix.yaml)" >> $GITHUB_OUTPUT

  docker:
    name: Build ${{ matrix.name }} (${{ matrix.build-target }})
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ inputs.build }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v5
        id: build-amd64
        with:
          context: artifacts
          load: true
          platforms: linux/amd64
          file: Dockerfile-ci
          target: ${{ matrix.build-target }}
          tags: suzhaobao-local:amd64
          build-args: |
            ARTIFACT_PREFIX=suzhaobao-${{ inputs.tag-prefix }}

      - name: Build Docker image (arm64)
        uses: docker/build-push-action@v5
        id: build-arm64
        with:
          context: artifacts
          load: true
          platforms: linux/arm64
          file: Dockerfile-ci
          target: ${{ matrix.build-target }}
          tags: suzhaobao-local:arm64
          build-args: |
            ARTIFACT_PREFIX=suzhaobao-${{ inputs.tag-prefix }}

      - name: Configure DockerHub
        uses: docker/login-action@v3
        if: ${{ inputs.push }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get tag info
        id: tags
        run: |
          set -x

          tag=micross/suzhaobao:${{ inputs.tag-prefix }}${{ matrix.tag-suffix }}
          echo "tag=${tag}" >> $GITHUB_OUTPUT

          if [[ "${{ inputs.environment }}" == "stable" ]]; then
            major=$(echo ${{ inputs.tag-prefix }} | tr "." "\n" | sed -n 1p)
            minor=$(echo ${{ inputs.tag-prefix }} | tr "." "\n" | sed -n 2p)
            echo "tags=${tag},micross/suzhaobao:${major}.${minor}${{ matrix.tag-suffix }},micross/suzhaobao:${major}${{ matrix.tag-suffix }}"  >> $GITHUB_OUTPUT
          else
            echo "tags=${tag}"  >> $GITHUB_OUTPUT
          fi

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        if: ${{ inputs.push }}
        with:
          context: artifacts
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile-ci
          target: ${{ matrix.build-target }}
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            ARTIFACT_PREFIX=suzhaobao-${{ inputs.tag-prefix }}

      - name: Pull docker image
        id: image-pull
        if: ${{ inputs.push }}
        run: |
          docker pull '${{ steps.tags.outputs.tag }}'

      - name: Push to DockerHub (latest)
        uses: docker/build-push-action@v5
        if: ${{ inputs.push && inputs.latest }}
        with:
          context: artifacts
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile-ci
          target: ${{ matrix.build-target }}
          tags: micross/suzhaobao:latest${{ matrix.tag-suffix }}
          build-args: |
            ARTIFACT_PREFIX=suzhaobao-${{ inputs.tag-prefix }}
